version: '3.9'

services:
  agendahub:
    image: agendahub:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - agendahub-network

networks:
  agendahub-network:
    driver: bridge

volumes:
  data-protection-keys:
